---
# defaults file for kvm_provision
base_image_name: CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
base_image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/{{ base_image_name }}
base_image_sha: eefeb2f6b57f9de9f96662f1f610503c3653dd21498e365c69366b9772833125
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: centos9-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: cs2023
cleanup_tmp: false
ssh_key: /root/.ssh/id_rsa.pub

